### ISSUE TITLE
Refactor erc20 tests 

### ISSUE THREAD

**Issue by anilCSE** [CosmWasm/cosmwasm-examples#57]
It's more of a question than an issue.
Looks like there are couple of redundant/replacable utility funtions in tests which can be avoided using contract's `QueryMsg`

For example here: https://github.com/CosmWasm/cosmwasm-examples/blob/master/erc20/tests/integration.rs#L23-L63
and here,
https://github.com/CosmWasm/cosmwasm-examples/blob/master/erc20/src/tests.rs#L23-L63

I would like to know your views around this

**Comment by webmaster128** [comment]
Very good question.

Those tests are very different things:
- **unit tests**: test the Rust logic directly, no compilation to Wasm, no VM involved, compiled using the cargo unit testing infrastructure for library internal interfaces.
- ***integration tests*: uses `cosmwasm_vm` to test a compiled Wasm, can only access symbols that are public exports of `cw_erc20`. More or less a standalone binary.

The only code those two types of tests share is the contract itself (i.e. things exported by `src/lib.rs`). While it would theoretically be possible to share test code between the two different test modules, I don't see an obvious place to put that code. Creating test utils that are exported by the contract would be part of the contract that is uploaded to chain since every public interface cannot be stripped off.

Most of those function would not be useful in the contract itself since they panic on error instead of propagating it up, which makes them handy to use in tests.

Even if it would be possible to DRY this a little more, I don't see any obvious potential without adding much more complexity and indirection, which would it make harder for newcomers to understand what is going on.

**Comment by anilCSE** [comment]
Makes sense, thank you for the clarification

**Comment by webmaster128** [comment]
You're welcome, closing for now.

> Creating test utils that are exported by the contract would be part of the contract that is uploaded to chain since every public interface cannot be stripped off.

I need to add that I'm not sure about this statement. I did not verify it. Wasm compilation could potentially remove everything that is not references by Wasm imports/exports. Anyways, I still don't think test helpers belong in the contract code.
